blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from . import views


app_name = 'blog'

urlpatterns = [
    path('comment/<int:pk>/', views.CreateComment.as_view(), name='create_comment'),
    path('', views.HomeView.as_view(), name='home'),
    path('<slug:slug>/', views.PostListView.as_view(), name='post_list'),
    path('<slug:slug>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_single'),
    # path('', cache_page(60 * 15)(views.HomeView.as_view()), name='home')

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('contact.urls', namespace='contact')),
    path('', include('blog.urls', namespace='blog')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('feedback/', views.CreateContact.as_view(), name='feedback')
]

blog/models.py
from ckeditor.fields import RichTextField
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey


class Category(MPTTModel):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    parent = TreeForeignKey('self', related_name='children', on_delete=models.SET_NULL, null=True, blank=True)

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField(upload_to='images/')
    text = models.TextField()
    category = models.ForeignKey(Category, related_name='post', on_delete=models.SET_NULL, null=True)
    tags = models.ManyToManyField(Tag, related_name='post')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_single", kwargs={"slug": self.category.slug, "post_slug": self.slug})

    def get_recipe(self):
        return self.recipe.all()

    def get_comments(self):
        return self.comment.all()


class Recipe(models.Model):
    name = models.CharField(max_length=100)
    serves = models.CharField(max_length=50)
    prep_time = models.PositiveIntegerField(default=0)
    cook_time = models.PositiveIntegerField(default=0)
    ingredients = RichTextField()
    directions = RichTextField()
    post = models.ForeignKey(Post, related_name='recipe', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    website = models.CharField(max_length=150, blank=True, null=True)
    message = models.TextField(max_length=500)
    created_at = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey(Post, related_name='comment', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

contact/models.py
from django.db import models
from ckeditor.fields import RichTextField


class ContactModel(models.Model):
    """Класс модели обратной связи"""
    name = models.CharField(max_length=50)
    email = models.EmailField()
    website = models.URLField(blank=True, null=True)
    message = models.TextField(max_length=5000)
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name} - {self.email}'


class ContactLink(models.Model):
    """Класс модели контактов"""
    icon = models.FileField(upload_to='icons/')
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class About(models.Model):
    """Класс модели страницы о нас"""
    name = models.CharField(max_length=50, default='')
    text = RichTextField()
    mini_text = RichTextField()

    def get_first_image(self):
        item = self.about_images.first()
        return item.image.url

    def get_images(self):
        return self.about_images.order_by('id')[1:]


class ImageAbout(models.Model):
    """Класс модели изображений страницы о нас"""
    image = models.ImageField(upload_to='about/')
    page = models.ForeignKey(About, on_delete=models.CASCADE, related_name='about_images')
    alt = models.CharField(max_length=100)


class Social(models.Model):
    '''Класс модели соц сетей страницы о нас'''
    icon = models.FileField(upload_to='icons/')
    name = models.CharField(max_length=200)
    link = models.URLField()

    def __str__(self):
        return self.name

gallery/models.py
from django.db import models


class Photo(models.Model):
    name = models.CharField(max_length=250)
    image = models.ImageField(upload_to='gallery')
    captions = models.TextField(blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Gallery(models.Model):
    name = models.CharField(max_length=250)
    image = models.ManyToManyField(Photo)
    captions = models.TextField(max_length=250, blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ['created_at', 'post']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'name'}),
            'email': forms.EmailInput(attrs={'placeholder': 'email'}),
            'website': forms.TextInput(attrs={'placeholder': 'website'}),
            'message': forms.Textarea(attrs={'placeholder': 'message'}),
        }

contact/forms.py
from django import forms
from .models import ContactModel


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactModel
        fields = '__all__'

blog/views.py
from django.shortcuts import render
from django.views import generic

from .forms import CommentForm
from .models import Post, Comment


class HomeView(generic.ListView):
    model = Post
    paginate_by = 9
    template_name = 'blog/home.html'


class PostListView(generic.ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(category__slug=self.kwargs.get('slug')).select_related('category')


class PostDetailView(generic.DetailView):
    model = Post
    context_object_name = 'post'
    slug_url_kwarg = 'post_slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        return context


class CreateComment(generic.CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        form.instance.post_id = self.kwargs.get('pk')
        self.object = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return self.object.post.get_absolute_url()

contact/views.py
from django.shortcuts import render
from .forms import ContactForm
from django.views import generic, View
from .models import ContactLink, About


class ContactView(View):
    def get(self, request):
        contacts = ContactLink.objects.all()
        form = ContactForm()
        return render(request, 'contact/contact.html', {'contacts': contacts, 'form': form})


class CreateContact(generic.CreateView):
    form_class = ContactForm
    success_url = '/'


class AboutView(View):
    def get(self, request):
        about = About.objects.last()
        return render(request, 'contact/about.html', {'about': about})

gallery/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}



<head>
  <meta charset="UTF-8">
  <meta name="description" content="Foodeiblog Template">
  <meta name="keywords" content="Foodeiblog, unica, creative, html">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Foodeiblog | Template</title>

  <!-- Google Font -->
  <link
      href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,600,700,800,900&display=swap"
      rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Unna:400,700&display=swap" rel="stylesheet">

  <!-- Css Styles -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>

<body>

<!-- Page Preloder -->
<div id="preloder">
  <div class="loader"></div>
</div>

<!-- Humberger Begin -->
{% include 'blog/include/left_nav.html' %}
<!-- Humberger End -->

<!-- Header Section Begin -->
    {% include 'header.html' %}
<!-- Header Section End -->

{% block content %}

{% endblock content %}

{% include 'footer.html' %}

<!-- Search Begin -->
<div class="search-model">
  <div class="h-100 d-flex align-items-center justify-content-center">
    <div class="search-close-switch">+</div>
    <form class="search-model-form">
      <input type="text" id="search-input" placeholder="Search here.....">
    </form>
  </div>
</div>
<!-- Search End -->

<!-- Js Plugins -->
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/blog/base.html
{% extends 'base.html' %}

{% block content %}
<section class="categories categories-grid spad">
    <div class="categories__post">
        <div class="container">
            <div class="categories__grid__post">
                <div class="row">
                    <div class="col-lg-8 col-md-8">
                        <div class="breadcrumb__text">
                            <h2>Categories: <span>{{ post_list.first.category.name }}</span></h2>
                            <div class="breadcrumb__option">
                                <a href="#">Home</a>
                                <span>Recipes</span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                {% for post in post_list %}
                                <div class="categories__post__item">
                                  <div class="categories__post__item__pic small__item set-bg"
                                       data-setbg="{{ post.image.url }}">
                                    <div class="post__meta">
                                      <h4>{{ post.created_at|date:"d" }}</h4>
                                      <span>{{ post.created_at|date:"M" }}</span>
                                    </div>
                                  </div>
                                  <div class="categories__post__item__text">
                                    <span class="post__label">{{ post.category }}</span>
                                    <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                                    <ul class="post__widget">
                                      <li>by <span>{{ post.author }}</span></li>
                                      <li>3 min read</li>
                                      <li>20 Comment</li>
                                    </ul>
                                    <p>{{ post.text|slice:":250" }}</p>
                                  </div>
                                </div>
                                {% endfor %}

                            </div>

                            <div class="col-lg-12 text-center">
                                <div class="load__more__btn">
                                    <a href="#">Load more</a>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/blog/include/left_nav.html
{% load menu_tags social_tags cache %}

{% cache 5000 left_nav %}
<div class="humberger__menu__overlay"></div>
    <div class="humberger__menu__wrapper">
        <div class="humberger__menu__logo">
            <a href="/"><img src="img/humberger/humberger-logo.png" alt=""></a>
        </div>
        <nav class="humberger__menu__nav mobile-menu">
            <ul>
                <li><a href="/">Главная</a></li>
                {% get_categories %}
                <li><a href="{% url 'contact:about' %}">О нас</a></li>
                <li><a href="{% url 'contact:contact' %}">Контакты</a></li>
            </ul>
        </nav>
        <div id="mobile-menu-wrap"></div>
        <div class="humberger__menu__about">
            <div class="humberger__menu__title sidebar__item__title">
                <h6>About me</h6>
            </div>
            {% get_about as about %}
            <img src="{{ about.get_first_image }}" alt="">
            {{ about.mini_text|safe }}
            <div class="humberger__menu__about__social sidebar__item__follow__links">

                {% get_social_links as social_links %}
                {% for item in social_links %}
                <a href="{{ item.link }}"><img class="contact_icon" src="{{ item.icon.url }}"></a>
                {% endfor %}

            </div>
        </div>
        <div class="humberger__menu__subscribe">
            <div class="humberger__menu__title sidebar__item__title">
                <h6>Subscribe</h6>
            </div>
            <p>Subscribe to our newsletter and get our newest updates right on your inbox.</p>
            <form action="#">
                <input type="text" class="email-input" placeholder="Your email">
                <label for="agree-check">
                    I agree to the terms & conditions
                    <input type="checkbox" id="agree-check">
                    <span class="checkmark"></span>
                </label>
                <button type="submit" class="site-btn">Subscribe</button>
            </form>
        </div>
    </div>
{% endcache %}

templates/blog/include/sidebar.html
{% load social_tags cache %}

{% cache 5000 sidebar %}

<div class="col-lg-4 col-md-4">
    <div class="sidebar__item">
        <div class="sidebar__about__item">
            <div class="sidebar__item__title">
                <h6>About me</h6>
            </div>
            {% get_about as about %}
            <img src="{{ about.get_first_image }}" alt="">
            <h6>Hi every one! I,m <span>{{ about.name }}</span></h6>
            <p>{{ about.mini_text|safe }}</p>
            <a href="{% url 'contact:about' %}" class="primary-btn">Read more</a>
        </div>
        <div class="sidebar__follow__item">
            <div class="sidebar__item__title">
                {% get_social_links as social_links %}
            </div>
            <div class="sidebar__item__follow__links">
                {% for item in social_links %}
                    <a href="{{ item.link }}"><img src="{{ item.icon.url }}"></a>
                {% endfor %}
            </div>
        </div>

        <div class="sidebar__item__banner">
            <img src="/static/img/sidebar/banner.jpg" alt="">
        </div>
        <div class="sidebar__item__categories">
            <div class="sidebar__item__title">
                <h6>Categories</h6>
            </div>
            {% include 'blog/include/tags/sidebar_category.html' %}

        </div>
        <div class="sidebar__subscribe__item">
            <div class="sidebar__item__title">
                <h6>Subscribe</h6>
            </div>
            <p>Subscribe to our newsletter and get our newest updates right on your inbox.</p>
            <form action="#">
                <input type="text" class="email-input" placeholder="Your email">
                <label for="s-agree-check">
                    I agree to the terms & conditions
                    <input type="checkbox" id="s-agree-check">
                    <span class="checkmark"></span>
                </label>
                <button type="submit" class="site-btn">Subscribe</button>
            </form>
        </div>
    </div>
</div>
{% endcache %}

templates/blog/include/tags/gallery_tag.html
<section class="hero">
    <div class="hero__slider owl-carousel">
        <div class="hero__item">
            <div class="container-fluid">
                <div class="row">
                    {% for photo in photos %}
                    <div class="col-lg-6 p-0">

                            <div class="hero__inside__item hero__inside__item--wide set-bg"
                                data-setbg="{{ photo.image.url }}">
                            </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>

templates/blog/include/tags/sidebar_category.html
{% load mptt_tags menu_tags %}
<ul>
{% get_list_category as list_category %}
{% recursetree list_category %}
<li>
    <a href="{% url 'blog:post_list' node.slug %}">{{ node.name }}</a>
    {{ children }}
</li>
{#    {% if node.is_child_node %}#}
{#    <li class="p-left"><a href="{% url 'blog:post_list' node.slug %}">{{ node.name }}</a></li>#}
{#        #}
{#    {% endif %}#}
{#</li>#}
{#    {% if not node.is_leaf_node %}#}
{#        <ul class="children">#}
{#            {{ children }}#}
{#        </ul>#}
{#    {% endif %}#}
{% endrecursetree %}
</ul>





            

templates/blog/include/tags/top_menu.html
{% load mptt_tags %}

<li class="dropdown">
    <a href="#">Категории</a>
    <ul class="dropdown__menu">
        {% recursetree list_category %}
        <li>
            <a href="{% url 'blog:post_list' node.slug %}">{{ node.name }}</a>
            {% if not node.is_leaf_node %}
                <ul class="children">
                    {{ children }}
                </ul>
            {% endif %}
        </li>
        {% endrecursetree %}
    </ul>
</li>

templates/blog/include/top_nav.html
{% load menu_tags cache %}

{% cache 5000 topnav %}
<nav class="header__menu">
    <ul>
        <li class="active"><a href="/">Главная</a></li>

        {% get_last_posts %}
        {% get_categories %}

        <li><a href="{% url 'contact:about' %}">О нас</a></li>
        <li><a href="{% url 'contact:contact' %}">Контакты</a></li>
    </ul>
</nav>
{% endcache %}

templates/blog/post_detail.html
{% extends 'base.html' %}
{% load social_tags %}
{% load static %}


{% block content %}
    <!-- Single Post Section Begin -->
<section class="single-post spad">
    <div class="single-post__hero set-bg" data-setbg="{{ post.image.url }}"></div>
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-lg-8">
                <div class="single-post__title">
                    <div class="single-post__title__meta">
                        <h2>{{ post.created_at|date:"d" }}</h2>
                        <span>{{ post.created_at|date:"M" }}</span>
                    </div>
                    <div class="single-post__title__text">
                        <ul class="label">
                            <li>Vegan</li>
                            <li>{{ post.category }}</li>
                        </ul>
                        <h4>{{ post.title }}</h4>
                        <ul class="widget">
                            <li>by {{ post.author }}</li>
                            <li>3 min read</li>
                            <li>20 Comment</li>
                        </ul>
                    </div>
                </div>
                <div class="single-post__social__item">
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="#"><i class="fa fa-youtube-play"></i></a></li>
                    </ul>
                </div>
                <div class="single-post__top__text">
                    <p>{{ post.text|truncatewords:20 }} </p>
                </div>
                <div class="single-post__recipe__details">
                    {% for recipe in post.get_recipe.all %}
                    <div class="single-post__recipe__details__option">
                        <ul>
                            <li>
                                <h5><i class="fa fa-user-o"></i> SERVES</h5>
                                <span>{{ recipe.serves}}</span>
                            </li>
                            <li>
                                <h5><i class="fa fa-clock-o"></i> PREP TIME</h5>
                                <span>{{ recipe.prep_time }}</span>
                            </li>
                            <li>
                                <h5><i class="fa fa-clock-o"></i> Cook TIME</h5>
                                <span>{{ recipe.cook_time }}</span>
                            </li>
                            <li><a href="#" class="primary-btn"><i class="fa fa-print"></i> Read more</a></li>
                        </ul>
                    </div>

                    <div class="single-post__recipe__details__indegradients">
                        <h5>Ingredients</h5>
                        {{ recipe.ingredients|safe }}

                    </div>
                    <div class="single-post__recipe__details__direction">
                        <h5>Directions</h5>
                        {{ recipe.directions|safe }}

                    </div>
                    {% endfor %}
                </div>


                <div class="single-post__desc">
                    <p>{{ post.text }}</p>
                </div>

                <div class="single-post__tags">
                    {% for tag in post.tags.all %}
                    <a href="#">{{ tag.name }}</a>
                    {% endfor %}
                </div>
                <div class="single-post__next__previous">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <a href="#" class="single-post__previous">
                                <h6><span class="arrow_carrot-left"></span> Previous posts</h6>
                                <div class="single-post__previous__meta">
                                    <h4>08</h4>
                                    <span>Aug</span>
                                </div>
                                <div class="single-post__previous__text">
                                    <span>Dinner</span>
                                    <h5>The Best Weeknight Baked <br />Potatoes, 3 Creative Ways</h5>
                                </div>
                            </a>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <a href="#" class="single-post__next">
                                <h6>Next posts <span class="arrow_carrot-right"></span> </h6>
                                <div class="single-post__next__meta">
                                    <h4>05</h4>
                                    <span>Aug</span>
                                </div>
                                <div class="single-post__next__text">
                                    <span>Smoothie</span>
                                    <h5>The $8 French Rosé I Buy in <br />Bulk Every Summer</h5>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                {% get_about as about %}
                <div class="single-post__author__profile">
                    <div class="single-post__author__profile__pic">
                        <img src="{{ about.get_first_image }}" alt="">
                    </div>
                    <div class="single-post__author__profile__text">
                        <h4>{{ about.name }}</h4>
                        <p>{{ about.mini_text|safe }}</p>
                        <div class="single-post__author__profile__social">
                            {% get_social_links as social_links %}
                            {% for item in social_links %}
                                <a href="{{ item.link }}"><img src="{{ item.icon.url }}"></a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="single-post__comment">
                    <div class="widget__title">
                        <h4>{{ post.comment.count }} Comment</h4>
                    </div>
                    {% for comment in post.get_comments %}
                    <div class="single-post__comment__item">
                        <div class="single-post__comment__item__pic">
                            <img src="/static/img/categories/cat-2.jpg" alt="">
                        </div>
                        <div class="single-post__comment__item__text">
                            <h5>{{ comment.name }}</h5>
                            <span>{{ comment.created_at }}</span>
                            <p>{{ comment.message }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="single-post__leave__comment">
                    <div class="widget__title">
                        <h4>Leave a comment</h4>
                    </div>
                    <form action="{% url 'blog:create_comment' pk=post.id %}" method="POST">
                        {% csrf_token %}
                        <div class="input-list">
                            {{ form.name }}
                            {{ form.email }}
                            {{ form.website }}
{#                                <input type="text" placeholder="Name">#}
{#                                <input type="text" placeholder="Email">#}
{#                                <input type="text" placeholder="Website">#}
                        </div>
                            {{ form.message }}
{#                            <textarea placeholder="Message"></textarea>#}
                        <button type="submit" class="site-btn">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
    <!-- Single Post Section End -->
{% endblock content %}


templates/contact/contact.html
{% extends 'base.html' %}

{% block content %}
    <section class="contact spad">
    <div class="container">
        <div class="contact__text">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h2>Contact</h2>
                        <div class="breadcrumb__option">
                            <a href="#">Home</a>
                            <span>Contact</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-md-6">
{#                    <div class="contact__map">#}
{#                        <iframe#}
{#                            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d96748.5538666784!2d-74.25209557318462!3d40.73139236772185!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25370329a0e1d%3A0xe1bcdc2adcfee473!2sNewark%2C%20NJ%2C%20USA!5e0!3m2!1sen!2sbd!4v1585643782289!5m2!1sen!2sbd"#}
{#                            height="350" style="border:0;" allowfullscreen="" aria-hidden="false"#}
{#                            tabindex="0"></iframe>#}
{#                    </div>#}
                    <div class="contact__widget">
                        <ul>
                            {% for contact in contacts %}
                            <li>
{#                                <i class="fa fa-map-marker"></i>#}
                                <img class="contact_icon" src="{{ contact.icon.url }}">
                                <span>{{ contact.name }}</span>
                            </li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="contact__form">
                        <div class="contact__form__title">
                            <h2>gET IN TOUCH</h2>
                            <p>My experience with Realy is absolutely positive. The themes are beautifully designed
                                and well documented. Realy theme provides quick support.</p>
                        </div>
                        <form action="{% url 'contact:feedback' %}" method="POST">
                            {% csrf_token %}
{#                            <input type="text" placeholder="Name">#}
{#                            <input type="text" placeholder="Email">#}
{#                            <input type="text" placeholder="Website">#}
{#                            <textarea placeholder="Message"></textarea>#}
                            {{ form }}
                            <button type="submit" class="site-btn">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}